version: '3'

services:
  mariadb:
    image: docker.io/library/mariadb:11.0.3
    network: slirp4netns:port_handler=slirp4netns
    container_name: mariadb
    env_file:
    - env/basic.env
    - env/mariadb.env
    ports:
    - 3306:3306
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /var/lib/podman/data/mariadb/pass:/run/secrets/mariadb_password:ro
    - /var/lib/podman/data/mariadb/data:/var/lib/mysql
  pdns:
    image: docker.io/pschiffe/pdns-mysql:latest
    network: slirp4netns:port_handler=slirp4netns
    container_name: pdns
    env_file:
    - env/basic.env
    - env/pdns.env
    depends_on:
    - mariadb
    ports:
    - "8154:53"
    - "8154:53/udp"
    - "8081:8081"
    volumes:
    - /etc/localtime:/etc/localtime:ro
